### ISSUE TITLE
Twitter passportjs.org implementation. Reward: 40 USD

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/Login-WRIO-App#11]
All the same https://github.com/webRunes/Login-WRIO-App/issues/1 but for Twitter

**Comment by AlexeyAnshakov** [comment]
Widget is working now
wrio.s3-website-us-east-1.amazonaws.com/Login-WRIO-App/Widget/login.html
but after login we have to return on page with "Logged via twitter" and logout button

**Comment by egorzalenski** [comment]
just need replace callback URL by logout page ("https://twitter.com by" => "http://wrio.s3-website-us-east-1.amazonaws.com/Login-WRIO-App/Widget/logout.html") in the twitter aplication and login.html

**Comment by AlexeyAnshakov** [comment]
So, please replace and create a pull request

**Comment by AlexeyAnshakov** [comment]
Though demo on http://188.226.149.163:5000/logintwitter is working, we need a logout button after successful login.
