### ISSUE TITLE
CRON auto start

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/Login-WRIO-App#216]
Please make sure 
/srv/www/login/current/expire.sh
is working on daily basis.

**Comment by AlexeyAnshakov** [comment]
It's done, @michbil please check.

**Comment by AlexeyAnshakov** [comment]
Reduce to 7 day

**Comment by umairadeeb** [comment]
Is this not required anymore?

**Comment by AlexeyAnshakov** [comment]
@michbil do we need additional efforts for the task?

**Comment by michbil** [comment]
Task done
