### ISSUE TITLE
Password or secret passprase

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/Login-WRIO-App#223]
Решить какой будет первоначальная версия защиты аккаунта:
1. автогенерация 12 символьного пароля либо ввод пользователем любого пароля от 1 до 64 символов. Будем указывать, что пароль не сохраняется у нас и не может быть восстановлен, пользователь должен сохранить его
2. автогенерация парольной фразы аля dark wallet (предпочтительный вариант)

**Comment by AlexeyAnshakov** [comment]
Первоначальный адрес кошелька с нашим автосгенерированным паролем будет храниться у нас в БД. Пользователю будет рекомендоваться создать новый кошелек с парольной фрзой см. п. 2. После чего средства с первого кошелька будут перенесены на второй, который и будет использоваться впредь. Решить вопрос с пополнением кошелька эфиром и переводом донейтов с него.

**Comment by michbil** [comment]
Passphrase generation lib used in darkwallet https://github.com/ggozad/mnemonic.js

**Comment by AlexeyAnshakov** [comment]
Отлично. Применим
