### ISSUE TITLE
sessionStorage

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/Login-WRIO-App#224]
Should we use sessionStorage
http://stackoverflow.com/questions/5523140/html5-local-storage-vs-session-storage
http://www.geekchamp.com/html5-tutorials/18-html5-session-storage
to avoid pinging server every time we load a page?

**Comment by michbil** [comment]
Мы можем ускорить логин при помощи создании своей версии cross-storage, которая будет доступна всем для чтения, но доступна на запись только для login.wrioos.com
Это позволит получить мгновенный логин, и не снизит безопасность.

**Comment by AlexeyAnshakov** [comment]
Ок. Сделаем позже.

**Comment by AlexeyAnshakov** [comment]
https://github.com/webRunes/Login-WRIO-App/issues/262
